settings:
    start_dir: .
    show_icons: true
    enable_logging: false
    pretty_markdown: true
    borderless: false
theme:
    app_theme: "~/.config/fm/themes/mocha.json"
    syntax_theme:
        light: pygments
        dark: dracula
